### ISSUE TITLE
unable to use model selection syntax in tests

### ISSUE THREAD

**Issue by Adusei** [mjirv/dbt-datamocktool#16] opened 2021-09-24 20:04 UTC
### Describe the bug
I'm unable to get these tests picked up in model selection syntax, but my test do get picked up when I run the entire test suite

### Steps to reproduce
`core/intermediate/schema.yml`
```
- name: chat_message_windowed
  +tags: chat_messages
  tests:
    - dbt_datamocktool.unit_test:
        input_mapping:
          ref('dim__date'): ref('dim__date_seed')
          ref('chat_message_extended'): ref('chat_message_extended_seed')
        expected_output: ref('chat_message_windowed_seed')
  columns:
  - name: chat_id
    tests:
      - not_null
  - name: chat_message_id
    tests:
      - unique
      - not_null
```

running `dbt test -m chat_message_windowed` picks up the three schema tests, but not the mock test

```
15:07:34 | Concurrency: 1 threads (target='dev')
15:07:34 |
15:07:34 | 1 of 3 START test not_null_chat_message_windowed_chat_id............. [RUN]
15:07:35 | 1 of 3 PASS not_null_chat_message_windowed_chat_id................... [PASS in 1.06s]
15:07:35 | 2 of 3 START test not_null_chat_message_windowed_chat_message_id..... [RUN]
15:07:37 | 2 of 3 PASS not_null_chat_message_windowed_chat_message_id........... [PASS in 1.37s]
15:07:37 | 3 of 3 START test unique_chat_message_windowed_chat_message_id....... [RUN]
15:07:38 | 3 of 3 PASS unique_chat_message_windowed_chat_message_id............. [PASS in 1.19s]
15:07:38 |
15:07:38 | Finished running 3 tests in 4.86s.

Completed successfully

Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
```

However, if i run all the test, i do see these tests get picked up - furthermore, running the test explicitly is see the tests _do_ run

`dbt test -m dbt_datamocktool_unit_test_chat_message_windowed_ref_chat_message_windowed_seed___ref_dim__date_seed___ref_chat_message_extended_seed_`

yields the following

```
Running with dbt=0.20.2
Found 498 models, 418 tests, 0 snapshots, 4 analyses, 378 macros, 3 operations, 8 seed files, 93 sources, 0 exposures

15:09:46 | Concurrency: 1 threads (target='dev')
15:09:46 |
15:09:46 | 1 of 1 START test dbt_datamocktool_unit_test_chat_message_windowed_ref_chat_message_windowed_seed___ref_dim__date_seed___ref_chat_message_extended_seed_ [RUN]
15:09:52 | 1 of 1 FAIL 636 dbt_datamocktool_unit_test_chat_message_windowed_ref_chat_message_windowed_seed___ref_dim__date_seed___ref_chat_message_extended_seed_ [FAIL 636 in 6.11s]
15:09:52 |
15:09:52 | Finished running 1 test in 8.18s.

Completed with 1 error and 0 warnings:

Failure in test dbt_datamocktool_unit_test_chat_message_windowed_ref_chat_message_windowed_seed___ref_dim__date_seed___ref_chat_message_extended_seed_ (models/marts/core/intermediate/intermediate.yml)
  Got 636 results, configured to fail if != 0

  compiled SQL at target/compiled/nursefly_dwh/models/marts/core/intermediate/intermediate.yml/schema_test/dbt_datamocktool_unit_test_cha_4fc1bb97185c98b5c4d5b0a4068bf79c.sql

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Expected results
I would expect that when i run `dbt test -m chat_message_windowed` that in addition to the three schema tests that the dbt mock test would run

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.3
  - package: mjirv/dbt_datamocktool
    version: 0.1.4
```

**Which database are you using dbt with?**
- [x] snowflake

**The output of `dbt --version`:**
```
installed version: 0.20.2
   latest version: 0.20.2

Up to date!

Plugins:
  - bigquery: 0.20.2
  - snowflake: 0.20.2
  - redshift: 0.20.2
  - postgres: 0.20.2
```

### Are you interested in contributing the fix?
Absolutely!

**Comment by sphinks** [comment] 2021-09-30 17:23
Get the same issue! Once run only one model, dbt_mock test does not start. Once run all tests or point it with the name - it runs.

**Comment by mjirv** [comment] 2021-10-16 20:58
Really interesting. Looking into it now. I think it has to do with [this change](https://docs.getdbt.com/reference/node-selection/test-selection-examples) from dbt v0.20.0:

> This can be complex for tests with multiple parents (e.g. relationships, or custom tests that ref() multiple models). To prevent tests from running when they aren't wanted, a test will be indirectly selected only if ALL of its parents are included by the selection criteria. If any parent is missing, that test won't run. On the other hand, if ANY parent is excluded, the test will be aggressively excluded as well

**Comment by mjirv** [comment] 2021-10-16 23:58
Hi @Adusei and @sphinks. Thanks for raising this.

I confirmed it is because of the dbt-core change mentioned above. Personally I don't really like that change and think tests should be "greedy" by default, but for now you can run it via the `--greedy` flag or by including _all_ the models referenced by the test. 

See below for examples of without and with `--greedy`:
```
$dbt test -m stg_customers dmt__raw_customers_1 dmt__expected_stg_customers_1
Running with dbt=0.21.0
Found 6 models, 23 tests, 0 snapshots, 0 analyses, 353 macros, 0 operations, 7 seed files, 1 source, 0 exposures

Some tests were excluded because at least one parent is not selected. Use the --greedy flag to include them.
  - dbt_datamocktool_unit_test_stg_customers_This_test_is_a_unit_test__ref_dmt__expected_stg_customers_2____dmt_raw_customers___Raw_Customers_2
  - dbt_datamocktool_unit_test_stg_customers_ref_dmt__expected_stg_customers_1___ref_dmt__raw_customers_1_

19:51:27 | Concurrency: 1 threads (target='dev')
19:51:27 |
19:51:27 | 1 of 2 START test not_null_stg_customers_customer_id................. [RUN]
19:51:27 | 1 of 2 PASS not_null_stg_customers_customer_id....................... [PASS in 0.12s]
19:51:27 | 2 of 2 START test unique_stg_customers_customer_id................... [RUN]
19:51:27 | 2 of 2 PASS unique_stg_customers_customer_id......................... [PASS in 0.08s]
19:51:27 |
19:51:27 | Finished running 2 tests in 0.41s.

Completed successfully
```

```
$ dbt test -m stg_customers --greedy
Running with dbt=0.21.0
Found 6 models, 23 tests, 0 snapshots, 0 analyses, 353 macros, 0 operations, 7 seed files, 1 source, 0 exposures

19:52:56 | Concurrency: 1 threads (target='dev')
19:52:56 | 
19:52:56 | 1 of 4 START test dbt_datamocktool_unit_test_stg_customers_This_test_is_a_unit_test__ref_dmt__expected_stg_customers_2____dmt_raw_customers___Raw_Customers_2 [RUN]
19:52:57 | 1 of 4 PASS dbt_datamocktool_unit_test_stg_customers_This_test_is_a_unit_test__ref_dmt__expected_stg_customers_2____dmt_raw_customers___Raw_Customers_2 [PASS in 0.46s]
19:52:57 | 2 of 4 START test dbt_datamocktool_unit_test_stg_customers_ref_dmt__expected_stg_customers_1___ref_dmt__raw_customers_1_ [RUN]
19:52:57 | 2 of 4 PASS dbt_datamocktool_unit_test_stg_customers_ref_dmt__expected_stg_customers_1___ref_dmt__raw_customers_1_ [PASS in 0.14s]
19:52:57 | 3 of 4 START test not_null_stg_customers_customer_id................. [RUN]
19:52:57 | 3 of 4 PASS not_null_stg_customers_customer_id....................... [PASS in 0.08s]
19:52:57 | 4 of 4 START test unique_stg_customers_customer_id................... [RUN]
19:52:57 | 4 of 4 PASS unique_stg_customers_customer_id......................... [PASS in 0.08s]
19:52:57 | 
19:52:57 | Finished running 4 tests in 0.92s.

Completed successfully
```

Closing since this is expected behavior for all dbt tests at the moment.

**Closed by mjirv** 2021-10-16 23:58 UTC
Labels: bug
